travis:
  secure:
    BINSTAR_TOKEN: idjFzGrL6fAOjFaEvBw3ToZ/CGBtQv9OVNGtm+6plorqXIQmkZX2RpDMeAkAxtiwBqc5GqWdttvKsuw1R55a9nyWbXvViIH+GLxyh45cnQCPdsomA1PmNMikimr4NnN7NyYfzBVLYozNP1WGEsKKCv6rLH7InKcNrxsOEQwvbZB9XOK9Y1uKQEJY3mgyc49G0bBZitGnai+9EV1ZPlnpdmuJ418CYDyo7iOavjjy7/cSOklMuo7jkbM0TWYjAgSF7Yavirv9xtdChipqt2cnyF42bK8u1leg+BLiZShxajp98pS1U6a4Ob8L+KhMCkcX42d4WVsw3BILCgoBVWQAXyxzPuwh4SAFptj6uDsTexEvYgzXjh+7MiLfkIcDDltQmkGcEMk398qXDbBra2O0boBS4O6bTTrkO6A12Zwi8MTpJO1WUfnzDSqrAOhJ564GGrPaW4uyqzXqHUd3ZqLXB21u+2vCBBIAfgE8spS46UJTqj9MrTgYM31zW5/KMKwptF+uCazDhAbpLlBTlGyH1R16zfa7dcgmZ5G+chOsKsszGwdetnUlgc+hOLkaNs3rplI49m1peBW1AoV4P7VLARszABsXbtQZckoPi0AqlMsMAuLgL99H5O1dI7ZSf/pvA2aVpf+gwus65zkRAzmWdrSdbBifr+vACrLBtFpEfj0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
